[package]
name = "nanoshogi"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
derivative = "2.2.0"
nom = "8.0.0"
ordered-float = "5.1.0"
rayon = "1.11.0"
smallvec = "1.15.1"
thiserror = "2.0.17"

# Turn this on for flamegraph
[profile.release]
debug = true
